#!/usr/bin/env python3

from sys import argv, exit
from Crypto.Hash import keccak

def keccak40(preimage):
  # compute keccak256
  keccak256 = keccak.new(digest_bits=256)
  preimage = bytes(preimage, 'utf-8') if type(preimage == 'str') else preimage
  keccak256.update(preimage) 
  hash256 = keccak256.digest()

  # modify it to get keccak40
  # Use byte 1 then bytes 15-17 in reverse order, then byte 4
  hash40 = hash256[1:2] + hash256[17:14:-1] + hash256[4:5]
  return hash40


if not(len(argv) == 2):
  print('Usage: {} <preimage>'.format(argv[0]))
  exit(1)


stringOutput = '0x{}'.format(keccak40(argv[1]).hex())
print(stringOutput)
